query DhtReadingsByTimeRange {
	getDhtReadingsByTimeRange(
		startTs: "2021-03-19T00:01:24.697092Z"
		endTs: "2023-06-30T00:01:24.697092Z"
	) {
		_id
		tempFahr
		tempCel
		humidity
		modifiedAt
		createdAt
	}
}